org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# ✅ Add this line for Android 15 (API 35) support
android.suppressUnsupportedCompileSdk=35

MY_KEYSTORE_FILE=keystore.jks
MY_KEYSTORE_PASSWORD=agni2025
MY_KEY_ALIAS=my-key-alias
MY_KEY_PASSWORD=agni2025
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# Disable incremental compilation to prevent "different roots" cross-drive build errors
kotlin.incremental=false

# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
