// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpCY8IKlX-M2lImiIkS8lB7z_ARxky_A',
    appId: '1:704229396210:web:4c8f6d23dfec40e5de0a6b',
    messagingSenderId: '704229396210',
    projectId: 'agni-car-app',
    authDomain: 'agni-car-app.firebaseapp.com',
    storageBucket: 'agni-car-app.firebasestorage.app',
    measurementId: 'G-80PHHP64RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxJvzK1HxsvEzPU2omrjUVgKnhKzHrA8',
    appId: '1:704229396210:android:7ff001942b7660bdde0a6b',
    messagingSenderId: '704229396210',
    projectId: 'agni-car-app',
    storageBucket: 'agni-car-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7hamB5ji7Kkrp3gt5fM137E8EXV-MyCk',
    appId: '1:704229396210:ios:0103e08e0366184ede0a6b',
    messagingSenderId: '704229396210',
    projectId: 'agni-car-app',
    storageBucket: 'agni-car-app.firebasestorage.app',
    iosBundleId: 'com.example.agnidriver2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7hamB5ji7Kkrp3gt5fM137E8EXV-MyCk',
    appId: '1:704229396210:ios:0103e08e0366184ede0a6b',
    messagingSenderId: '704229396210',
    projectId: 'agni-car-app',
    storageBucket: 'agni-car-app.firebasestorage.app',
    iosBundleId: 'com.example.agnidriver2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDpCY8IKlX-M2lImiIkS8lB7z_ARxky_A',
    appId: '1:704229396210:web:92a83501a5a73b90de0a6b',
    messagingSenderId: '704229396210',
    projectId: 'agni-car-app',
    authDomain: 'agni-car-app.firebaseapp.com',
    storageBucket: 'agni-car-app.firebasestorage.app',
    measurementId: 'G-54ZG21D1C9',
  );

}