// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ CORRECT PROJECT: agnicarrentaldriver-8fb07
  // Package: com.AgniDriver.agnidriver2025
  // Sender ID: 1006622748598

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ek1VqFekyprDlnfWivoCzXDuxQQgCyI',
    appId: '1:1006622748598:android:dc364a107b815ebdbc1b17',
    messagingSenderId: '1006622748598',
    projectId: 'agnicarrentaldriver-8fb07',
    storageBucket: 'agnicarrentaldriver-8fb07.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ek1VqFekyprDlnfWivoCzXDuxQQgCyI',
    appId: '1:1006622748598:android:dc364a107b815ebdbc1b17',
    messagingSenderId: '1006622748598',
    projectId: 'agnicarrentaldriver-8fb07',
    storageBucket: 'agnicarrentaldriver-8fb07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ek1VqFekyprDlnfWivoCzXDuxQQgCyI',
    appId: '1:1006622748598:android:dc364a107b815ebdbc1b17',
    messagingSenderId: '1006622748598',
    projectId: 'agnicarrentaldriver-8fb07',
    storageBucket: 'agnicarrentaldriver-8fb07.firebasestorage.app',
    iosBundleId: 'com.AgniDriver.agnidriver2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ek1VqFekyprDlnfWivoCzXDuxQQgCyI',
    appId: '1:1006622748598:android:dc364a107b815ebdbc1b17',
    messagingSenderId: '1006622748598',
    projectId: 'agnicarrentaldriver-8fb07',
    storageBucket: 'agnicarrentaldriver-8fb07.firebasestorage.app',
    iosBundleId: 'com.AgniDriver.agnidriver2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ek1VqFekyprDlnfWivoCzXDuxQQgCyI',
    appId: '1:1006622748598:android:dc364a107b815ebdbc1b17',
    messagingSenderId: '1006622748598',
    projectId: 'agnicarrentaldriver-8fb07',
    storageBucket: 'agnicarrentaldriver-8fb07.firebasestorage.app',
  );
}